### ISSUE TITLE
Repository key expired

### ISSUE THREAD

**Issue by fernando0010** [sektioneins/suhosin#120]
Looks like they key and/or the cert on https://sektioneins.de/files/repository.asc has expired.

`W: Error de GPG: http://repo.suhosin.org debian-jessie Release: Las siguientes firmas no fueron válidas: KEYEXPIRED 1596097255 KEYEXPIRED 1596097255 KEYEXPIRED 1596097255`

```
--2020-08-22 02:16:47--  https://sektioneins.de/files/repository.asc
Resolviendo sektioneins.de (sektioneins.de)... 159.69.28.73, 2a01:4f8:c0c:f413::1
Conectando con sektioneins.de (sektioneins.de)[159.69.28.73]:443... conectado.
ERROR: El certificado de “sektioneins.de” no es confiable.
ERROR: El certificado de “sektioneins.de” ha expirado.

```

**Comment by bef** [comment]
Yes, who would have thought, that someone is still using suhosin for PHP5 on Debian. I highly suggest to upgrade to PHP7.
I will most likely keep the expired certificate in order to discourage people from using outdated and unmaintained software. Just in case you really really need suhosin (for PHP5) for research or other reasons, you are free to compile it yourself from source.

Just in case you were wondering, PHP7 does not come with Suhosin support at the moment (Mid 2020), but the new Suhosin-NG Project in on its way to support PHP7, 8 and a number of thrilling new features, likely some time later this year. See https://github.com/sektioneins/suhosin-ng
